### ISSUE TITLE
Document usage outside of composer?

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-php#1]
@splatEric would it be worth documenting non-Composer installs? I've had issues in the past with developers not familiar with Composer who couldn't figure out how to use a library outside of that ecosystem. Not sure if Composer is 100% the default these days.

**Comment by splatEric** [comment]
Personally I don't think it's worth it. Composer handles the dependency of the guzzle http package that is being used in this code, and that (naturally) has dependencies as well. This makes manually requiring all the relevant files a real headache, so you would essentially wind up writing an autoloader outside of composer that would be doing much the same thing.

It's a well defined, well supported standard in the same vein as ruby gems, it seems a waste of time and effort to produce an alternative.

**Comment by cbetta** [comment]
Ok agreed, makes no sense indeed.
