### ISSUE TITLE
Incoming query limit not working

### ISSUE THREAD

**Issue by StefanoCesena** [interfax/interfax-php#10]
Hello,
I'm trying to retrieve a list of inbounded faxes, but limit option works only for values lesser than 25 (the default value).
I'm having troubles with the following code:

```
    $interfax = new Client(['username' => $username, 'password' => $password]);

    $inbound = $interfax->inbound;
    $faxes = $inbound->incoming(['limit' => 29]); 
```

Please help,
Thank you

**Comment by ricky-shake-n-bake-bobby** [comment]
Per the System Limitations (https://help.uplandsoftware.com/interfax/en/send-faxes/system-limitations.htm?Highlight=System%20Limitations), the REST API is limited to 25 transactions at time, so that behaviour is expected.
