### ISSUE TITLE
Bring documentation in line with Ruby/Node/Python/Java libraries

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-php#2]
@splatEric can we bring the README formatting in line with the other docs? Have a look at the Ruby/Node/Python/Java libraries and you see we mostly used the same syntax throughout. For maintenance purposes please can we stick as much as possible to this flow?

**Comment by splatEric** [comment]
The README structure is based on the ruby library README ... can you clarify what discrepancies you are concerned about?

**Comment by cbetta** [comment]
@splatEric it's kinda of but not completely. Please use the template laid out in the Ruby library to bring things in line.

For example, the PHP README:

<img width="569" alt="screen shot 2016-10-19 at 10 53 02" src="https://cloud.githubusercontent.com/assets/7718/19514114/59904c48-95ea-11e6-99d4-9af276eb3ef0.png">

and the Ruby README:

<img width="574" alt="screen shot 2016-10-19 at 10 53 06" src="https://cloud.githubusercontent.com/assets/7718/19514121/633cc154-95ea-11e6-9132-cb87c91a7743.png">

**Comment by splatEric** [comment]
Okay, I've gone through and brought it more into line with the ruby readme, although obviously there are some discrepancies as it is not implemented in exactly the same way.

**Comment by cbetta** [comment]
@splatEric perfect
