### ISSUE TITLE
Issue with file names in multiple file fax

### ISSUE THREAD

**Issue by mikeaveli007** [interfax/interfax-php#3]
When using the 'files' param and using a filename like "test (1).pdf" along with another file I am getting an error 'Problem with POST request: Content not available'.  If I use the 'file' param instead and filename of "test (1).pdf" it works.  If I use say "test 1.pdf" and another file then that also works.  For some reason it won't work when sending it with another file.

**Comment by cbetta** [comment]
@mikeaveli007 thank you for reporting. Could you share a code sample of the code you're using? I just want to make sure we're talking about the same thing.

**Comment by mikeaveli007** [comment]
The following code is what fails:
`$client = new Client(['username' => $username, 'password' => $password]);`
`$fax = $client->deliver([
	'faxNumber' => $faxnumber, 
	'files' => ["files/test.pdf", "files/test (1).pdf"]
]);
`

**Comment by mikeaveli007** [comment]
I tried sending each file as a stream but I get the same error.  Next I tried creating an `Interfax\Document` for each file and then sending those as an array to the `files` param and that did work.  Files size on these test pdfs are very small and only 1 page each.

**Comment by eyalnevo** [comment]
@mikeaveli007  We have identified that the issue with the how the library is using the file names that you provide.
We are working on a fix that will make it ignorant to the file name - however, for the time being, you can try to change the names of the files you are using to a name that does not have spaces or parenthesis "(,)" and then try again.
We will let you know once we have a working fix for this issue.

**Comment by mikeaveli007** [comment]
Ok, thank you.  For now I am using as a work around a check that will create a `Interfax\Document` if the filename has parenthesis.

**Comment by eyalnevo** [comment]
@mikeaveli007 we have released version 1.1.1 of the library which should this issue. Please try it and let us know if there any further issues that you find.

**Comment by mikeaveli007** [comment]
Just tried it and it did indeed work, thank you.
