### ISSUE TITLE
feedback: non-composer install

### ISSUE THREAD

**Issue by apic68** [interfax/interfax-php#7]
For those of us that do not use composer, it would be nice if there were directions for a traditional PHP installation.  Not one that requires me to download composer. (step 2 - Inside the Interfax PHP directory, download composer...)

**Comment by splatEric** [comment]
This was resolved from version 1.0.2 onward. You can download the zip directly from the release page on GitHub. Please see the readme for more details

**Comment by splatEric** [comment]
The readme update has hopefully clarified the alternate approaches to installing the package.
